# -*- coding: utf-8 -*-
"""StringReverser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oHd8F6i6dK0gbUFPDD3JMqJuVcakJG6p
"""

def reverse_string(string):
  reverseString = string[::-1]
  return reverseString

word = "dog"
reverse_string(word)